config/routes.rb
Ciudadio::Application.routes.draw do
  #mount TransportAdder::Engine => "/mobility"  
  
  devise_for :admins, :only => [:sessions]
  namespace :admins do
    get '/' => 'main#index', :as => :index
    
    get '/evaluations' => 'evaluations#index', :as => :evaluations_index
    get '/evaluations/new' => 'evaluations#new', :as => :evaluations_new
    post '/evaluations' => 'evaluations#create', :as => :evaluations
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords" }, :only => [:passwords, :omniauth_callbacks]
  
  devise_scope :user do
    get "/sign_up", :to => "devise/registrations#new"
    get "/sign_in", :to => "devise/sessions#new", :as => "new_user_session"
    delete "/sign_out", :to => "devise/sessions#destroy", :as => "destroy_user_session"
    
    namespace :users do
      post '/auth/create', :to => "omniauth_callbacks#create", :as => :auth_sign_up
      delete '/auth/cancel', :to => "omniauth_callbacks#cancel", :as => :cancel_auth_sign_up
    end
    
    post "/account/create", :to => "devise/registrations#create"
    delete "/account/deactivate", :to => "devise/registrations#destroy"
    get "/account/recover_password", :to => "devise/passwords#new"
    get "/account/reset_password", :to => "devise/passwords#edit", :as => "edit_user_password"

    post "/log_in", :to => "devise/sessions#create", :as => "user_session"
  end
  
  namespace :settings do
    get "account", :via => :get
    get "access", :via => :get
    get "profile", :via => :get
    put "changed", :via => :put
  end
  
  get '/places/' => 'places#index'
  post "/places/" => "places#create"
  put "/places/:id" => "places#update"
  get "/places/new" => 'places#new', :as => "new_place"
  
  namespace :places do
    get 'search' => 'searches#main'
    post 'search' => 'searches#execute_main'
    
    get ":place_id/announcements" => 'announcements#index', :as => "announcements"
    post ":place_id/announcements" => 'announcements#create'
    delete ":place_id/announcements/:id" => 'announcements#destroy', :as => "delete_announcement"
    
    get ":place_id/comments" => 'comments#index', :as => "comments"
    post ":place_id/comments" => 'comments#create'
    delete ":place_id/comments/:id" => 'comments#destroy', :as => "delete_comment"
    
    get ":place_id/recommendations" => 'recommendations#index', :as => "recommendations"
    put ":place_id/recommendations/on" => 'recommendations#update', :as => 'recommendation_on', :defaults => { :recommend => 'on' }
    put ":place_id/recommendations/off" => 'recommendations#update', :as => 'recommendation_off', :defaults => { :recommend => 'off' }
    
    post ':place_id/evaluations/' => 'evaluations#create', :as => "evaluations"
    put ":place_id/evaluations/:id" => "evaluations#update", :as => "evaluation"
    get ':place_id/evaluations/new' => 'evaluations#new', :as => 'new_evaluation'
    get ":place_id/evaluations/edit/:id" => "evaluations#edit", :as => "edit_evaluation"
    get ":place_id/evaluations" => "evaluations#show"
  end
  
  namespace :map do
    resources :street_marks, :only => [:create, :index, :show]
    resources :incidents, :except => [:edit, :update] do
      collection do 
        post :filtering
      end
    end
  end

  get "/places/:id" => 'places#show', :as => "place"
  get "/places/edit/:id" => 'places#edit', :as => "edit_place"

  
  
  
  root :to => 'welcome#index'
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  include Shared::Geography
  include Kinds
  
  belongs_to :user
  belongs_to :bike_item
  
  validates_length_of :description, :maximum => 130
  validates_length_of :bike_description, :maximum => 130, :if => :theft_or_assault?
  validates_presence_of :coordinates, :kind, :description
  validates :vehicle_identifier, :format => /[A-Z0-9]{4}/, :allow_blank => true, :if => :accident_or_regulation_infraction?
  validates_presence_of :bike_description, :if => :theft_or_assault?
  
  attr_protected :user_id
  
  def self.new_with(params, coordinates, user)
    user= user.nil? ? new(params) : new(params.merge(:user => user)) 
    user.apply_geo(coordinates)
    user
  end
  
  def self.date_filtering_options
    { 1 => :last_week, 2 => :last_month, 3 => :last_year, 4 => :all }
  end
  
  def self.date_filtering_option_for(option)
    self.date_filtering_options.invert[option]
  end
  
  def self.humanized_date_filtering_options
    self.date_filtering_options.keys.each.inject({}) do |collected, key| 
      collected[key] = humanized_date_filtering_option_for(key)
      collected
    end
  end
  
  def self.humanized_date_filtering_option_for(key)
    I18n.t("incidents.filtering.fields.date")[date_filtering_options[key]]
  end
  
  def self.filtering_with(params={})
    params = {} if params.eql?(:nothing)
    query=String.new
    values={}
    
    if params[:type]
      kinds_selected = params[:type].keys.each.inject(String.new) do |collected, last|
        collected += "#{Incident.kind_for(last.to_sym)},"
        collected
      end
      
      query += "kind IN (#{kinds_selected.chop})"
    end
    
    unless params[:complaint_issued].blank?
      query += " AND " unless query.blank?
      query += " complaint_issued = :complaint_issued"
      values.merge!({:complaint_issued =>  params[:complaint_issued] == "true" }) 
    end
    
    if end_date=range_date_for(params[:range_date])
      query += " AND " unless query.blank?
      query += " date_and_time >= :end_date"
      values.merge!({ :end_date => end_date })
    end
    
    if params[:map_enabled]
      polygon_given = self.make_polygon(params[:coordinates])
      unless polygon_given.nil?
        query += " AND " unless query.blank?
        query += "ST_Within(incidents.coordinates, ST_GeomFromEWKT(E'#{polygon_given.as_hex_ewkb}'))"
      end
    end
    
    categorized_by_kinds Incident.where(query, values)
  end
  
  def self.categorized_by_kinds(incidents=nil)
    (incidents || all).each.inject({:total => 0}) do |collected, incident| 
      collected[:total] += 1
      collected[incident.kind] ||= []
      collected[incident.kind] << incident
      collected
    end
  end
  
  def owned_by_user?(passed_user)
    return false if passed_user.nil?
    user = passed_user
  end
  
  def self.range_date_for(option)
    return false if(option.nil? || Incident.date_filtering_option_for(:all) == option)
    now = Time.now
    case option.to_i
    when Incident.date_filtering_option_for(:last_week)
      now-1.week
    when Incident.date_filtering_option_for(:last_month)
      now-1.month
    when Incident.date_filtering_option_for(:last_year)
      now-1.year
    end
  end
  
end

app/models/incident/kinds.rb
module Incident::Kinds
  
  module ClassMethods
    def kinds
      { 1 => :theft, 2 => :assault, 3 => :accident, 4 => :regulation_infraction }
    end
    
    def humanized_kinds
      self.kinds.keys.each.inject({}) do |collected, key| 
        collected[key] = I18n.t("incidents.kinds.#{self.kinds[key]}")
        collected
      end
    end
    
    def kind_for(kind)
      self.kinds.invert[kind]
    end
    
    def humanized_kind_for(kind)
      I18n.t("incidents.kinds.#{kind}")
    end
  end
  
  def self.included(base)
    base.extend(ClassMethods)
  end
  
  def humanized_kind
    Incident.humanized_kind_for(symbol_kind)
  end
  
  def symbol_kind
    Incident.kinds[kind]
  end
  
  def is_of_kind?(kind)
    symbol_kind==kind
  end
  
  def theft_or_assault?
    symbol_kind.eql?(:theft) || symbol_kind.eql?(:assault)
  end
  
  def accident_or_regulation_infraction?
    symbol_kind.eql?(:regulation_infraction) || symbol_kind.eql?(:accident)
  end
end

app/controllers/map/base_controller.rb
class Map::BaseController < ActionController::Base
  layout 'map'
end

app/controllers/map/incidents_controller.rb
class Map::IncidentsController < Map::BaseController
  
  def new
    @incident = Incident.new
  end
  
  def create
    @incident = Incident.new_with(params[:incident], params[:coordinates], current_user)
    
    if @incident.save
      flash[:posted_incident] = @incident
      redirect_to map_incidents_path, :notice => I18n.t('incidents.create.saved')
    else
      render :new
    end
  end
  
  def index
    @incidents = Incident.filtering_with(:nothing)
  end
  
  def destroy
    incident = Incident.find(params[:id])
    incident.destroy
    
    @incidents = Incident.filtering_with(:nothing)
    
    respond_to do |format|
      format.js
    end
  end
  
  def filtering
    @incidents = Incident.filtering_with(params[:incident])
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/map/street_marks_controller.rb
class Map::StreetMarksController < Map::BaseController  
  
  respond_to :json
  
  def index
    @street_marks = StreetMark.all
  end
  
  def create
    @street_mark = StreetMark.build_new(post_params.merge(:user_id => current_user))
    @street_mark.save
    respond_with @street_mark, :location => map_street_mark_url(@street_mark)
  end
  
  private
  def post_params
    params[:street_mark].slice(:name, :segment_path)
  end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
  
  def total_numbers_for(count)
    return t('incidents.index.numbers.total.one') if count == 1
    t('incidents.index.numbers.total.other', :count => count)
  end
  
  def incidents_collection(hash)
    hash.delete(:total)
    hash.values.flatten
  end
  
  def partial_numbers_for(ocurrences, kind, as_link=false)
    text=status_numbers_for(ocurrences, kind)
    result = as_link ? link_to(text, 'javascript:void(0);', :id => "#{kind}", :class => "group-toggle") : "<span class='#{kind}'>#{text}</span>"
    result.html_safe
  end
  
  def status_numbers_for(hash, kind)
    ocurrences = hash[Incident.kind_for(kind)]
    count = ocurrences == nil ? 0 : ocurrences.size
    count == 1 ? t("incidents.index.numbers.#{kind}.one") : t("incidents.index.numbers.#{kind}.other", :count => count)
  end
  
  def incident_types_for(incidents)
    incidents = [incidents] if incidents.is_a?(Symbol)
    with_incidents = incidents.each.inject(String.new) do |collected,incident|
      collected += " incident-#{Incident.kind_for(incident)}"
      collected
    end
    "#{with_incidents} incident-selectable"
  end
    
  def is_visible(incidents, object)
    incidents = [incidents] if incidents.is_a?(Symbol)
    incidents.each do |incident|
      return if Incident.kind_for(incident) == object.kind
    end
    "hidden"
  end 
  
  def reporter_of(incident)
    if incident.user.nil?
      t('incidents.index.list.item.reporter.anonymous')
    else
      t('incidents.index.list.item.reporter.user', :user => incident.user.username)
    end
  end
end

app/views/map/incidents/_filtering.html.erb
<% content_for :classes_for_map, "selectable-for-search" %>

<h2><%= t('incidents.filtering.title') %></h2>

<%= form_tag filtering_map_incidents_path, :remote => true do %>
	<div id="filtering-kind-list" class="group rounded-5">
		
		<%= check_box_tag "incident[type[theft]]" %>
		<span><%= t('incidents.kinds.theft') %></span>
		<br/>
		<%= check_box_tag "incident[type[assault]]" %>
		<span><%= t('incidents.kinds.assault') %></span>
		<br/>
		<%= check_box_tag "incident[type[accident]]" %>
		<span><%= t('incidents.kinds.accident') %></span>
		<br/>
		<%= check_box_tag "incident[type[regulation_infraction]]" %>
		<span><%= t('incidents.kinds.regulation_infraction') %></span>
		
	</div>
	<br/>
	
	<%= label_tag t('activerecord.attributes.incident.date_and_time') %>
	<div>
		<%= select_tag "incident[range_date]", options_for_select(Incident.humanized_date_filtering_options.invert) %>
	</div>
	
	<br/>
	<span class="as-label"><%= t('activerecord.attributes.incident.complaint_issued') %></span>
	<div>
		<%= select_tag "incident[complaint_issued]", 
				options_for_select({t('common_answers')[true] => true, t('common_answers')[false] => false}),  
				{:include_blank => true} %> 
	</div>
	
	<br/>
	<%= check_box_tag "incident[map_enabled]" %>
	<span class="as-label"><%= t('incidents.filtering.map_search') %></span>
	
	<%= hidden_field_tag 'incident[coordinates[sw]]]', {}, :id => 'coordinates_sw' %>
	<%= hidden_field_tag 'incident[coordinates[ne]]]', {}, :id => 'coordinates_ne' %>
	
	<div class="separator"></div>
	<div class="actions to-right">
		<%= link_to t('actions.close'), 'javascript:void(0);', :class=> "close-button" %>
		<%= submit_tag t('actions.accept'), :class => "button green-button", :id => 'filtering-start' %>
	</div>
<% end %>

app/views/map/incidents/_form.html.erb
<%= f.text_area :description, :cols => 48, :rows => 3, :placeholder => t('incidents.new.form.fields.description') %>
<div id="incident_description_count" class="field-counter"></div>

<div class="field">
	<%= f.check_box :complaint_issued, :checked => @incident.complaint_issued || false %>
	<%= f.label :complaint_issued, Incident.human_attribute_name(:complaint_issued), :style => 'display:inline-block' %>
</div>
<div class="field">
	<%= f.label :date_and_time, Incident.human_attribute_name(:date_and_time) %><br/>
	<%= f.datetime_select :date_and_time %>
</div>
<div class="field">
	<%= f.label :kind, Incident.human_attribute_name(:kind) %>
	<%= f.select :kind, options_for_select(Incident.humanized_kinds.invert, @incident.kind), {:include_blank => true} %>
</div>

<div class="field <%= is_visible(:theft, @incident) %> <%= incident_types_for(:theft) %>">	
	<%= f.label :attacher_used, Incident.human_attribute_name(:attacher_used) %>
	<%= f.select :bike_item_id, options_from_collection_for_select(BikeItem.all, "id", "name", @incident.bike_item_id), {:include_blank => true} %>
</div>
<div class="<%= is_visible([:theft, :assault], @incident) %> <%= incident_types_for([:theft, :assault]) %>">
	<%= f.text_area :bike_description, :cols => 48, :rows => 3, :placeholder => t('incidents.new.form.fields.bike_description') %>
	<div id="incident_bike_description_count" class="field-counter"></div>
</div>

<div class="<%= errors_for(:vehicle_identifier, @incident) %> 
						<%= is_visible([:accident, :regulation_infraction], @incident) %> 
						<%= incident_types_for([:accident, :regulation_infraction]) %>">
	<%= f.text_field :vehicle_identifier, :size => 33, :placeholder => t('incidents.new.form.fields.vehicle_identifier') %>
</div>

<br/>
<div class="note">
	<%= f.label :coordinates, t('incidents.new.form.fields.coordinates') %>
</div>
<%= hidden_field_tag "coordinates[lat]", @incident.coordinates.nil? ? "" : @incident.coordinates.lat %>
<%= hidden_field_tag "coordinates[lon]", @incident.coordinates.nil? ? "" : @incident.coordinates.lon %>

app/views/map/incidents/_incident.html.erb
<div id="<%= incident.id %>" class="item">
	<div class="description"><%= incident.description %></div>
	<div class="to-right">
		<span class="time"><%= distance_of_time_in_words(incident.date_and_time, Time.now, true) %></span> 
		<span class="reporter"><%= reporter_of(incident) %></span>
	</div>
	
	<div class="lat hidden"><%= incident.coordinates.lat %></div>
	<div class="lon hidden"><%= incident.coordinates.lon %></div>
	<%= link_to t('incidents.index.list.item.details'), 'javascript:void(0);', :class => "itemdetails-toggle see-details" %>
	
	<%= render :partial => 'map/incidents/details/extended', :locals => { :incident => incident } %>
</div>

app/views/map/incidents/_incident_ocurrence.html.erb
<div class="<%= kind %>">
	<% if as_link %>
		<%= link_to partial_numbers_for(@incident_ocurrence, kind), 'javascript:void(0);', :class => "#{kind}-toggle" %>
	<% else %>
		<%= partial_numbers_for(@incident_ocurrence, kind) %>
	<% end %>
</div>

app/views/map/incidents/_listing.html.erb
<div class="close-button"><%= t('actions.close') %></div>
<div id="default-group" class="hidden"><%= Incident.kinds.values.first %></div>
<div class="numbers">
	<%= partial_numbers_for(@incidents, :theft, true) %>
	<%= partial_numbers_for(@incidents, :accident, true) %>
	<%= partial_numbers_for(@incidents, :assault, true) %>
	<%= partial_numbers_for(@incidents, :regulation_infraction, true) %>
</div>
<br/>

<% [:theft, :accident, :assault, :regulation_infraction].each do |kind| %>
<div class="<%= kind %> kind-group">
	<% unless @incidents[Incident.kind_for(kind)].nil? %>
		<div class="paginated-<%= kind %>">
			<%= render @incidents[Incident.kind_for(kind)] %>
		</div>
		<script>
			$( ".paginated-<%= kind %>" ).easyPaginate({
				step: 4,
				nextprev: false
			});
		</script>
	<% else %>
		<p class="empty"><%= t('incidents.index.empty') %></p>
	<% end %>
</div>
<% end %>

app/views/map/incidents/_submenu.html.erb
<div class="options rounded-bottom-5 shadow-light">
	<%= link_to total_numbers_for(@incidents[:total]), 'javascript:void(0);', :class => "incidents-count itemlist-toggle" %>
	<%= link_to t('incidents.index.search'), 'javascript:void(0);', :class => "incidents-filter itemsfiltering-toggle" %>
</div>

<div class="status rounded-5 shadow-light">
	<div class="numbers">
		
		<% [:theft, :accident, :assault, :regulation_infraction].each do |category| %>
			<% text=status_numbers_for(@incidents, category) %>
			<div class="stat <%= category %>-s">
				<span class="number"><%= text[0,text.index(" ")] %></span>
				<p class="category"><%= text[text.index(" "), text.length] %></p>
			</div>
		<% end %>
		
	</div>
</div>

app/views/map/incidents/destroy.js.erb
$('#notifications').html("<%= t('incidents.destroy.success') %>").fadeIn(1000).delay(1000).fadeOut(500);
$('#itemdetails .close-button').click();
$('#submenu').html("<%= escape_javascript(render 'submenu') %>").hide().delay(2500).fadeIn(300);
$('#itemlist').html("<%= escape_javascript(render 'listing') %>");
mapIncidents();

app/views/map/incidents/filtering.js.erb
$('#submenu').html("<%= escape_javascript(render 'submenu') %>");
$('#itemlist').html("<%= escape_javascript(render 'listing') %>");
$('#itemsfiltering .close-button').click();

mapIncidents();

app/views/map/incidents/index.html.erb
<%= content_for :header do %>
	<h1><%= t('incidents.index.title') %><span class="type rounded-5"><%= t('incidents.index.kind.bike') %></span></h1>
	
	<div class="actions">
		<%= link_to t('incidents.index.new'), new_map_incident_path, :class => "button blue" %>
	</div>
<% end %>

<%= content_for :map_area do %>
	<div id="submenu"><%= render 'submenu' %></div>
	
	<div id="itemlist" class="incidents rounded-5 shadow-strong"><%= render 'listing' %></div>
	<div id="itemdetails" class="hidden rounded-5 shadow-light"></div>
	
	<div id="itemsfiltering" class="hidden rounded-bottom-5 shadow-light"><%= render 'filtering' %></div>
	
	<% if flash[:posted_incident] %>
		<div id="just-posted" class="hidden">
			<span class="kind"><%= flash[:posted_incident].symbol_kind %></span>
			<span class="id"><%= flash[:posted_incident].id %></span>
		</div>
	<% end %>
<% end %>

app/views/map/incidents/new.html.erb
<% content_for :classes_for_map, "is-editable" %>
<% content_for :classes_for_header, "hidden" %>

<%= content_for :map_area do %>
	
	<div id="newitem" class="rounded-5 shadow-strong">
		<h1><%= t('incidents.new.title') %><span class="type rounded-5"><%= t('incidents.index.kind.bike') %></span></h1>

		<p class="reporting-status">
		<% if user_signed_in? %>
			<%= t('incidents.new.reporting.as', :account => current_user.username) %>
		<% else %>
			<%= t('incidents.new.reporting.anonymously') %><br/>
			<%= t('incidents.new.reporting.invitation') %>
			<%= link_to t('actions.sessions.first_person.start').downcase, new_user_session_path %>
		<% end %>
		</p>
		<%= form_for([:map, @incident]) do |f| %>
		
			<% unless @incident.errors.empty? %>
				<h3 class="error-message"><%= t('actions.verify_fields_on_red') %></h3>
			<% end %>
			<div class="styled-form">
				<%= render :partial => 'form', :locals => {:f => f} %>
			</div>
			<div class="separator"></div>
			<div class="actions to-right">
				<%= link_to t('actions.cancel'), map_incidents_path %>
				<%= f.submit t('actions.save'), :class => 'submit blue button' %>
			</div>
		<% end %>
		
		
	</div>
	
<% end %>