config/routes.rb
Ciudadio::Application.routes.draw do
  #mount TransportAdder::Engine => "/mobility"  
  
  devise_for :admins, :only => [:sessions]
  namespace :admins do
    get '/' => 'main#index', :as => :index
    
    get '/evaluations' => 'evaluations#index', :as => :evaluations_index
    get '/evaluations/new' => 'evaluations#new', :as => :evaluations_new
    post '/evaluations' => 'evaluations#create', :as => :evaluations
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords" }, :only => [:passwords, :omniauth_callbacks]
  
  devise_scope :user do
    get "/sign_up", :to => "devise/registrations#new"
    get "/sign_in", :to => "devise/sessions#new", :as => "new_user_session"
    delete "/sign_out", :to => "devise/sessions#destroy", :as => "destroy_user_session"
    
    namespace :users do
      post '/auth/create', :to => "omniauth_callbacks#create", :as => :auth_sign_up
      delete '/auth/cancel', :to => "omniauth_callbacks#cancel", :as => :cancel_auth_sign_up
    end
    
    post "/account/create", :to => "devise/registrations#create"
    delete "/account/deactivate", :to => "devise/registrations#destroy"
    get "/account/recover_password", :to => "devise/passwords#new"
    get "/account/reset_password", :to => "devise/passwords#edit", :as => "edit_user_password"

    post "/log_in", :to => "devise/sessions#create", :as => "user_session"
  end
  
  namespace :settings do
    get "account", :via => :get
    get "access", :via => :get
    get "profile", :via => :get
    put "changed", :via => :put
  end
  
  get '/places/' => 'places#index'
  post "/places/" => "places#create"
  put "/places/:id" => "places#update"
  get "/places/new" => 'places#new', :as => "new_place"
  
  namespace :places do
    get 'search' => 'searches#main'
    post 'search' => 'searches#execute_main'
    
    get ":place_id/announcements" => 'announcements#index', :as => "announcements"
    post ":place_id/announcements" => 'announcements#create'
    delete ":place_id/announcements/:id" => 'announcements#destroy', :as => "delete_announcement"
    
    get ":place_id/comments" => 'comments#index', :as => "comments"
    post ":place_id/comments" => 'comments#create'
    delete ":place_id/comments/:id" => 'comments#destroy', :as => "delete_comment"
    
    get ":place_id/recommendations" => 'recommendations#index', :as => "recommendations"
    put ":place_id/recommendations/on" => 'recommendations#update', :as => 'recommendation_on', :defaults => { :recommend => 'on' }
    put ":place_id/recommendations/off" => 'recommendations#update', :as => 'recommendation_off', :defaults => { :recommend => 'off' }
    
    post ':place_id/evaluations/' => 'evaluations#create', :as => "evaluations"
    put ":place_id/evaluations/:id" => "evaluations#update", :as => "evaluation"
    get ':place_id/evaluations/new' => 'evaluations#new', :as => 'new_evaluation'
    get ":place_id/evaluations/edit/:id" => "evaluations#edit", :as => "edit_evaluation"
    get ":place_id/evaluations" => "evaluations#show"
  end
  
  namespace :map do
    resources :street_marks, :only => [:create, :index, :show]
    resources :incidents, :except => [:edit, :update] do
      collection do 
        post :filtering
      end
    end
  end

  get "/places/:id" => 'places#show', :as => "place"
  get "/places/edit/:id" => 'places#edit', :as => "edit_place"

  
  
  
  root :to => 'welcome#index'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  layout 'application'
  
  before_filter :authenticate_user!
  before_filter :expose_user
  
  def account
  end
  
  def access
  end
  
  def profile
  end
  
  def changed    
    params_hash = params[:user]
    params_hash.merge!(:current_password => params[:current_password]) if params.has_key?(:current_password)
    
    if @user.check_parameters_and_password(params_hash) && @user.update_attributes(params_hash)
      sign_in(@user, :bypass => true)
      flash[:notice] = I18n.t("user_accounts.settings.successful_save")
    else
      flash[:notice] = I18n.t("user_accounts.settings.unsuccessful_save")
    end
    
    redirect_to request.referer || 'account'    
  end
  
  private 
  
  def expose_user
    @user = current_user
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_shared_actions.html.erb
<h1><%=t "user_accounts.settings.title" %></h1>

<div class="accounts-settings">
	<%= link_to t('user_accounts.settings.account'), settings_account_path %>
	<%= link_to t('user_accounts.settings.access'), settings_access_path %>
	<%= link_to t('user_accounts.settings.profile'), settings_profile_path %>
</div>

<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/settings/access.html.erb
<%= render 'shared_actions' %>

<p>
	<span><%= t('user_accounts.settings.sections.access.reset_password') %></span>
	<%= form_for(@user, :url => user_password_path, :html => { :method => :post }) do |f| %>

	  <%= f.hidden_field :email, :value => @user.email %></div>

	  <div><%= f.submit t('user_accounts.settings.sections.access.reset') %></div>
	<% end %>
	<br/>
	<% unless @user.authorizations.empty? %>
		<span class="note"><%= t('user_accounts.settings.sections.access.external_reset') %></span>
	<% end %>
</p>


<%= form_for(@user, :url => settings_changed_path(@user), :html => { :method => :put }) do |f| %>
		
	<div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>
	
	<div><label for="password"><%=t('user_accounts.settings.sections.access.current_password') %></label><br />
  <%= password_field_tag :current_password %></div>
	
	<%= f.submit t("user_accounts.settings.save") %>
<% end %>

app/views/settings/account.html.erb
<%= render 'shared_actions' %>

<%= form_for(@user, :url => settings_changed_path(@user), :html => { :method => :put }) do |f| %>
	
	<div><%= f.label :full_name %><br />
  <%= f.text_field :full_name %></div>

	<div><%= f.label :email %><br />
  <%= f.email_field :email %></div>
	
	<div><%= f.label :username %><br />
  <%= f.text_field :username %></div>
	
	<div><%= f.label :share_location %>
  <%= f.check_box :share_location %></div><br/>

	<%= f.submit t("user_accounts.settings.save") %>
<% end %>

<%= link_to t("user_accounts.settings.sections.account.deactivate"), account_deactivate_path, 
	:confirm => t("user_accounts.settings.sections.account.deactivate_confirmation"), :method => :delete %>

app/views/settings/profile.html.erb
<%= render 'shared_actions' %>


<b><%= @user.full_name %></b><%=link_to t("user_accounts.settings.sections.profile.change_name"), settings_account_path %>

<%= form_for(@user, :url => settings_changed_path(@user), :html => { :method => :put }) do |f| %>
	
	<div><%= f.label :bio %><br />
  <%= f.text_area :bio %></div>

	<div><%= f.label :personal_page %><br />
  <%= f.text_field :personal_page %></div>
	
	<%= f.submit t("user_accounts.settings.save") %>
<% end %>