config/routes.rb
Ciudadio::Application.routes.draw do
  #mount TransportAdder::Engine => "/mobility"  
  
  devise_for :admins, :only => [:sessions]
  namespace :admins do
    get '/' => 'main#index', :as => :index
    
    get '/evaluations' => 'evaluations#index', :as => :evaluations_index
    get '/evaluations/new' => 'evaluations#new', :as => :evaluations_new
    post '/evaluations' => 'evaluations#create', :as => :evaluations
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords" }, :only => [:passwords, :omniauth_callbacks]
  
  devise_scope :user do
    get "/sign_up", :to => "devise/registrations#new"
    get "/sign_in", :to => "devise/sessions#new", :as => "new_user_session"
    delete "/sign_out", :to => "devise/sessions#destroy", :as => "destroy_user_session"
    
    namespace :users do
      post '/auth/create', :to => "omniauth_callbacks#create", :as => :auth_sign_up
      delete '/auth/cancel', :to => "omniauth_callbacks#cancel", :as => :cancel_auth_sign_up
    end
    
    post "/account/create", :to => "devise/registrations#create"
    delete "/account/deactivate", :to => "devise/registrations#destroy"
    get "/account/recover_password", :to => "devise/passwords#new"
    get "/account/reset_password", :to => "devise/passwords#edit", :as => "edit_user_password"

    post "/log_in", :to => "devise/sessions#create", :as => "user_session"
  end
  
  namespace :settings do
    get "account", :via => :get
    get "access", :via => :get
    get "profile", :via => :get
    put "changed", :via => :put
  end
  
  get '/places/' => 'places#index'
  post "/places/" => "places#create"
  put "/places/:id" => "places#update"
  get "/places/new" => 'places#new', :as => "new_place"
  
  namespace :places do
    get 'search' => 'searches#main'
    post 'search' => 'searches#execute_main'
    
    get ":place_id/announcements" => 'announcements#index', :as => "announcements"
    post ":place_id/announcements" => 'announcements#create'
    delete ":place_id/announcements/:id" => 'announcements#destroy', :as => "delete_announcement"
    
    get ":place_id/comments" => 'comments#index', :as => "comments"
    post ":place_id/comments" => 'comments#create'
    delete ":place_id/comments/:id" => 'comments#destroy', :as => "delete_comment"
    
    get ":place_id/recommendations" => 'recommendations#index', :as => "recommendations"
    put ":place_id/recommendations/on" => 'recommendations#update', :as => 'recommendation_on', :defaults => { :recommend => 'on' }
    put ":place_id/recommendations/off" => 'recommendations#update', :as => 'recommendation_off', :defaults => { :recommend => 'off' }
    
    post ':place_id/evaluations/' => 'evaluations#create', :as => "evaluations"
    put ":place_id/evaluations/:id" => "evaluations#update", :as => "evaluation"
    get ':place_id/evaluations/new' => 'evaluations#new', :as => 'new_evaluation'
    get ":place_id/evaluations/edit/:id" => "evaluations#edit", :as => "edit_evaluation"
    get ":place_id/evaluations" => "evaluations#show"
  end
  
  namespace :map do
    resources :street_marks, :only => [:create, :index, :show]
    resources :incidents, :except => [:edit, :update] do
      collection do 
        post :filtering
      end
    end
  end

  get "/places/:id" => 'places#show', :as => "place"
  get "/places/edit/:id" => 'places#edit', :as => "edit_place"

  
  
  
  root :to => 'welcome#index'
end

app/models/place.rb
class Place < ActiveRecord::Base
  include Shared::Geography
  include Opinions
  include Recommendations
  include Comments
  include Announcements
  include Geography
  include Search
  
  has_many :recommendations
  has_many :recommenders, :through => :recommendations, :source => :user
  
  has_many :announcements
  
  has_many :place_comments
  has_many :commenters, :through => :place_comments, :source => :user
  
  belongs_to :category
  has_many :surveys, :as => :evaluable
  
  validates_presence_of :name, :description, :category
  validate :coordinates_are_set, :twitter_correct_format
  
  def self.include_with(id, association)
    self.find(:first, :conditions => {:id => id}, :include => association)
  end

  def self.filtering_with(sort_order, categories=[])
    category_conds = {:category_id => categories}
    return Place.where(category_conds).order("mobility_kindness_index DESC") if(sort_order.to_s == "accessible")
    return Place.where(category_conds).order("created_at DESC") if(sort_order.to_s == "recent")
    return Place.where(category_conds).order("recommendations_count DESC") if(sort_order.to_s == "most_recommended")
    return Place.where(category_conds).order("mobility_kindness_index DESC, created_at ASC")
  end
  
  def self.new_with_owner(params, user)
    new_place = self.new(params)
    new_place.recommendations.build(:user => user, :is_owner => true, :place => new_place)
    new_place
  end
  
  def evaluation_from(user)
    Survey.where({:user_id => user.id, :evaluable_id => self.id, :evaluable_type => self.class.to_s}).first
  end
  
  def is_bike_friendly?
    is_bike_friendly
  end
  
  def evaluation_count_for(meta_answer_item) 
    self.surveys.joins(:answers).where(
                                    :answers => 
                                      {:meta_answer_item_id => meta_answer_item.id},
                                    :surveys => 
                                      {:evaluable_id => self.id, :evaluable_type => self.class.to_s}).count
  end
  
  private
  def twitter_correct_format
    return true if self.twitter.blank?
    errors.add(:base, I18n.t('places.custom_validations.twitter_bad_format')) if !self.twitter.match(/@(\w+)/).nil?
  end
  
end

app/models/place/announcements.rb
module Place::Announcements
  
  def add_announcement(user, params)
    return false if !self.verified_owner_is?(user) 
    announcement = Announcement.create({:announcer => user, :place => self}.merge(process_dates(params)))
    self.announcements << announcement
    announcement
  end
  
  private
  def process_dates(params)
    new_params = {}
    [:start_date, :end_date].each do |date|
      if params.has_key?(date) && params[date].is_a?(Hash)
        sd = params[date]
        new_params[date] = Time.local(sd["year"], sd["month"], sd["day"], sd["hour"], sd["minute"])
        params.delete(date)
      end
    end
    new_params.merge(params)
  end
end

app/models/place/comments.rb
module Place::Comments
  
  def update_comments_count
    self.update_attribute(:comments_count, PlaceComment.where("place_id" => self.id).count)
  end
  
  def add_comment(user, content)
    PlaceComment.create(:user => user, :place => self, :content => content)
  end
end

app/models/place/geography.rb
module Place::Geography
  private 
  def coordinates_are_set
    errors.add(:base, I18n.t('places.custom_validations.coordinates_missing')) if self.coordinates.nil?
  end
end

app/models/place/opinions.rb
module Place::Opinions
  
  def evaluation_from(user)
    Survey.where({:user_id => user.id, :evaluable_id => self.id, :evaluable_type => self.class.to_s}).first
  end
  
  def evaluation_count_for(meta_answer_item) 
    self.surveys.joins(:answers).where(
                                    :answers => 
                                      {:meta_answer_item_id => meta_answer_item.id},
                                    :surveys => 
                                      {:evaluable_id => self.id, :evaluable_type => self.class.to_s}).count
  end
end

app/models/place/recommendations.rb
module Place::Recommendations
  
  def update_recommendations_count
    self.update_attribute(:recommendations_count, Recommendation.where("place_id" => self.id).count)
  end
  
  def add_recommender(user, opts=[])
    Recommendation.create(:user => user, :place => self, :is_owner => opts.include?(:owner), :is_verified => opts.include?(:verified))
  end
  
  def recommended_by?(user)
    return false if user.nil?
    !self.recommendations.where("user_id = ?", user.id).empty?
  end
  
  def change_recommendation_status_for(user, status)
    recommend = self.recommendations.where("user_id = ?", user.id)
    if(recommend.empty? && status.to_sym == :on)
      self.add_recommender(user)
    elsif(!recommend.empty? && status.to_sym == :off)
      return false if recommend.first.is_owner
      recommend.first.delete
      update_recommendations_count
    end
  end
  
  # Ownings code
  
  def verified_owner_is?(user)
    return false if user.nil?
    !self.recommendations.where("user_id = ? AND is_owner = ? AND is_verified = ?", user.id, true, true).empty?
  end
  
  def owned_by?(user)
    return false if user.nil?
    !self.recommendations.where("user_id = ? AND is_owner = ?", user.id, true).empty?
  end
  
  def owners
    Recommendation.find(:all, :conditions => {:is_owner => true}, :include => :user)
  end
  
  def get_any_owner
    owner= owners.first
    return owner.user unless owner.nil?
    nil
  end
end

app/models/place/search.rb
module Place::Search
  module ClassMethods
    
    def find_by(params)
      params=params[:place]
      
      str_keys = String.new
      arr_vals = Array.new
      
      unless params[:name].blank?
        str_keys += "name ILIKE ?"
        arr_vals << "%#{params[:name]}%"
      end
      
      unless params[:description].blank?
        str_keys += " AND " unless str_keys.blank?
        str_keys += "description ILIKE ?"
        arr_vals << "%#{params[:description]}%"
      end
      
      unless params[:categories].blank?
        category_list = params[:categories].keys.each.inject("") do |result, word| 
          result += "#{word},"
          result 
        end
        
        str_keys += " AND " unless str_keys.blank?
        str_keys += "category_id IN (#{category_list.chop})"
      end
      
      if params[:map_enabled]
        polygon_given = self.make_polygon(params[:coordinates])
        if polygon_given
          str_keys += " AND " unless str_keys.blank?
          str_keys += "ST_Within(places.coordinates, ST_GeomFromEWKT(E'#{polygon_given.as_hex_ewkb}'))"
        end
      end
      
      self.find(:all, :conditions => [str_keys]+arr_vals)
    end
  end
  
  def self.included(base)
    base.extend(ClassMethods)
  end
end

app/controllers/places/announcements_controller.rb
module Places
  class AnnouncementsController < ApplicationController
  
    before_filter :authenticate_user!, :except => [:index]
  
    def index
      @place = Place.include_with(params[:place_id], :announcements)
      
      respond_to do |format|
        format.js
      end
    end
  
    def create
    
      @place = Place.find(params[:place_id])

      if (@announcement = @place.add_announcement(current_user, params[:announcement]))
        respond_to do |format|
          format.js 
        end
      else
        render(:nothing => true)
      end
    end
  
    def destroy
      @announcement = Announcement.find(params[:id])
      @place = @announcement.place
    
      if @place.verified_owner_is?(current_user)
        @announcement_destroyed = @announcement.destroy
    
        respond_to do |format|
          format.js 
        end
      else
        render(:nothing => true)
      end
    end
    
  end
end

app/controllers/places/comments_controller.rb
module Places
  class CommentsController < ApplicationController
    
    before_filter :authenticate_user!, :except => [:index]
    
    def index
      @place = Place.include_with(params[:place_id], :commenters)
      
      respond_to do |format|
        format.js
      end
    end
    
    def create
      @place = Place.find(params[:place_id])
      @place.add_comment(current_user, params[:place_comment][:content]) if user_signed_in?
      
      respond_to do |format|
        format.js 
      end
    end
    
    def destroy
      @place_comment = PlaceComment.find(params[:id])
      
      if @place_comment.owned_by?(current_user)
        @place = @place_comment.place
        @place_comment_destroyed = @place_comment.destroy
      
        respond_to do |format|
          format.js 
        end
      else
        render(:nothing => true)
      end
    end
    
  end
end

app/controllers/places/commits_controller.rb
module Places
  class CommitsController < ApplicationController
    
    before_filter :authenticate_user!
    
    def evaluate
      survey = Survey.from_hash(params[:survey].merge(:user_id => current_user.id))
      
      if survey.save
        respond_to do |format|
          format.js 
        end
      else
        render(:nothing => true)
      end
    end
    
  end
end

app/controllers/places/evaluations_controller.rb
class Places::EvaluationsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :find_place, :except => [:edit]
  
  def new
    respond_to do |format|
      format.js
    end
  end
  
  def show
  end
  
  def create
    @survey = Survey.from_hash(params[:survey].merge(:user => current_user, 
                                                     :evaluable => @place))
    @survey.save
    
    respond_to do |format|
      format.js { render 'show_listing' }
    end
  end
  
  def edit
    @survey = Survey.find(params[:id]) 
    @place = @survey.evaluable
    
    respond_to do |format|
      format.js
    end
  end
  
  def update
    @survey = Survey.from_hash(params[:survey].merge(:user => current_user, 
                                                     :evaluable => @place))
    if @survey.save
      Survey.find(params[:id]).destroy
    end
    
    respond_to do |format|
      format.js { render 'show_listing' }
    end
    
  end
  
  private 
  def find_place
    @place = Place.find(params[:place_id])
  end
end

app/controllers/places/recommendations_controller.rb
class Places::RecommendationsController < ApplicationController
    
  def index
    @place = Place.include_with(params[:place_id], :recommendations)
    
    respond_to do |format|
      format.js
    end
  end
  
  def update
    @place = Place.find(params[:place_id])
    
    if user_signed_in?
      @recommendation_status_changed = !@place.change_recommendation_status_for(current_user, params[:recommend])
    end
    
    respond_to do |format|
      format.js 
    end
  end
  
end

app/controllers/places/searches_controller.rb
module Places
  class SearchesController < ApplicationController
    layout 'map'
    
    def main
      @categories = Category.all
    end
    
    def execute_main
      @places = Place.find_by(params[:search])
      
      @search_mode = true
      render :template => 'places/index', :layout => 'places' 
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  layout 'places'
  
  before_filter :authenticate_user!, :except => [:index, :show]

  def new
    @place = Place.new
  end
  
  def edit
    @place = Place.find(params[:id])
  end
  
  def index
    if params.has_key?(:filtered)
      @places = Place.filtering_with(params[:ordered_by], params[:categories])
    else
      @categories = Category.all
      @places = Place.order("mobility_kindness_index DESC, created_at ASC")
    end
    
    respond_to do |format|
      format.html #index.html.erb
      format.js
    end
  end
  
  def show
    @place = Place.find(params[:id])
  end
  
  def create
    @place = Place.new_with_owner(params[:place], current_user)
    @place.apply_geo(params[:coordinates])
    
    respond_to do |format|
      if @place.save
        format.html { redirect_to(@place) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @place = Place.find(params[:id])
    @place.apply_geo(params[:coordinates])
    
    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

app/helpers/places_helper.rb
module PlacesHelper
  def categories_for_select
    Category.all.inject({}) do |hash, f| 
      hash[I18n.t("categories.all.#{f.standard_name}").to_sym] = f.id
      hash
    end
  end
end

app/views/places/_form.html.erb
<%= render :partial => 'shared/form_errors', :locals => {:message => "save_failure", :object => @place} %>


<%= p.text_field :name, :placeholder => t('places.views.form.name') %>
<%= p.select :category_id,  options_for_select(categories_for_select) %>

<br/>
<%= p.check_box :is_bike_friendly, :checked => @place.is_bike_friendly || false %>
<label><%= I18n.t("places.views.form.is_bike_friendly") %></label>

<%= p.text_area :description, :placeholder => t('places.views.form.description'), :rows => 3, :cols => 46 %>
<%= p.text_area :address, :placeholder => t('places.views.form.address'), :rows => 2, :cols => 46 %>

<%= p.text_field :twitter, :placeholder => t('places.views.form.twitter') %>

<%= hidden_field_tag 'coordinates[lat]', @place.coordinates.nil? ? "" : @place.coordinates.lat %>
<%= hidden_field_tag 'coordinates[lon]', @place.coordinates.nil? ? "" : @place.coordinates.lon %>

app/views/places/_unit.html.erb
<div id="place-<%= place.id %>" class="item rounded-5 inlined">
	<div class="order-<%= place_counter %>"></div>
	
	<div class="image"></div>
	<p class="name rounded-10"><%= link_to place.name, place_path(place) %></p>
	
</div>

app/views/places/edit.html.erb
<%= content_for(:top_container) do %>
	<div style="width:100%; height:300px; top:40px" id="map" class="is-editable displays-points radio-3 shadowed-light"></div>
<% end %>

<%= content_for :header do %>
	<div class="mini-header size-of-300 shadow-light rounded-bottom-5">
		<h1><%= t('places.views.index.title') %><span class="type rounded-5"><%= t('states.edit') %></span></h1>
		<ul class="inlined actions-list">
			<li><%= link_to "&larr; #{t('actions.return')}".html_safe, places_path, :class => 'plain' %></li>
		</ul>
	</div>
<% end %>

<p class="address selected-from-map"><%=t('places.views.new.instruction') %></p>

<%= content_for :form_container do %>
	<div class="simple-form rounded-top-5 shadow-light">
		<%= form_for @place, :method => :put do |p| %>
			<div class="styled-form">
				<%= render :partial => 'form', :locals => {:p => p} %>
			</div>
			<%= p.submit t('actions.update'), :class => "button blue to-right" %>
		<% end %>
	</div>
<% end %>

app/views/places/index.html.erb
<%= content_for(:top_container) do %>
	<div style="width:100%; height:400px; top: 40px; border-bottom: 3px solid #5E5E5E" id="map" class="displays-points radio-3 shadowed-light"></div>
<% end %>
<%= content_for(:classes_for_header, "middle-size") %>

<%= content_for :header do %>
	<div class="mini-header shadow-light rounded-bottom-5">
		<h1><%= t('places.views.index.title') %></h1>
		<ul class="inlined actions-list">
			<li><%= link_to t('places.views.index.new'), new_place_path, :class => "button blue" %></li>
			<li><%= link_to t('places.views.index.search'), places_search_path, :class => "button orange" %></li>
		</ul>
		<div class="separator"></div>
	
		<select id="l-params" class="inlined">
		  <option value="nothing"><%= t('places.views.index.all') %></option>
		  <option value="accessible"><%= t('places.views.index.accessible') %></option>
		  <option value="recent"><%= t('places.views.index.recent') %></option>
		  <option value="popular"><%= t('places.views.index.popular') %></option>
		</select>
	
		<%= render 'categories/all' %>
	</div>
<% end %>

<div id="l-places" class="places">
	<%= render :partial => 'places/unit', :collection => @places, :as => :place %>
</div>

<div id="side-box">
	
	<% unless user_signed_in? %>

		<div class="lgd_in_not">
			<%= link_to t('places.views.index.registration_invitation'), "" %>
		</div>
	<% end %>
</div>

<%= render 'places/searches/results_message' %>

app/views/places/index.js.erb
$('#l-places').html("<%= escape_javascript(render :partial => 'unit', :collection => @places, :as => :place).html_safe %>");

app/views/places/new.html.erb
<%= content_for(:top_container) do %>
	<div style="width:100%; height:300px; top:40px; border-bottom: 3px solid #5E5E5E" id="map" class="hide-address-on-load is-editable displays-points radio-3 shadowed-light"></div>
<% end %>

<%= content_for :header do %>
	<div class="mini-header size-of-300 shadow-light rounded-bottom-5">
		<h1><%= t('places.views.index.title') %><span class="type rounded-5"><%= t('states.new') %></span></h1>
		<ul class="inlined actions-list">
			<li><%= link_to "&larr; #{t('actions.return')}".html_safe, places_path, :class => 'plain' %></li>
		</ul>
	</div>
<% end %>

<p class="address selected-from-map"><%=t('places.views.new.instruction') %></p>

<%= content_for :form_container do %>
	<div class="simple-form rounded-top-5 shadow-light">
		<%= form_for @place do |p| %>
			<div class="styled-form">
				<%= render :partial => 'form', :locals => {:p => p} %>
			</div>
			<%= p.submit t('actions.save'), :class => "button blue to-right" %>
		<% end %>
	</div>
<% end %>

app/views/places/show.html.erb
<%= content_for :header do %>
	<div class="mini-header size-of-300 shadow-light rounded-bottom-5">
		<h1><%= t('places.views.index.title') %></h1>
		<ul class="inlined actions-list">
			<li><%= link_to "&larr; #{t('actions.return')}".html_safe, places_path %></li>
			<li><%= link_to t('places.views.index.search'), places_search_path, :class => "button orange" %></li>
		</ul>
	</div>
<% end %>

<div id="main-box">
	
	<div class="general">
		<h1><%= @place.name %> </h1>
		<span class="contributor">
			<b><%= t('connectives.by').downcase %> <%= @place.get_any_owner.username %></b>
			<% if @place.owned_by?(current_user) %>
				(<%= link_to t('places.views.show.edit'), edit_place_path(@place) %>)
			<% end %>
		</span>
		<p class="<%= "not-given-" unless @place.address.blank? %>address"><%= @place.address %></p>
		
		<ul class="social rounded-5">
			<li class="social-nets">
				<% unless @place.twitter.blank? %>
					<span class="twitter">@<%= link_to @place.twitter, "http://www.twitter.com/#{@place.twitter}", :target => "_blank" %></span>
				<% end %>
			</li>

			<li class="recommend actions">
				<%= render 'places/recommendations/action_link' %>	
			</li>
		</ul>
		
	</div>
	
	<p class="description"><%= @place.description %></p>

	<div class="mobility rounded-5 shadow-lighter">
		<ul>
			<% if @place.is_bike_friendly? %>
				<li><div class="bike"></div></li>
			<% end %>
			<li>
				<a href="javascript:void(0);" class="last">
					<span class='count'><%= 0 %></span>
					<span class='saying'><%= t('places.views.show.transports') %></span>
				</a>
			</li>
		</ul>
		<%= link_to t('places.views.show.how_to_arrive') , '', :class => "main rounded-5" %>
	</div>


	<div class="changing-content rounded-5 shadow-lighter">
		<ul id="status-bar" class="rounded-top-5">
		
			<li class="evaluations">
				<%= render 'places/evaluations/count' %>
			</li>
		
			<li class="photos">
				<a href="javascript:void(0);">
					<span class='count'><%= @place.photos_count %></span>
					<span class='saying'><%= t('places.views.show.photos') %></span>
				</a>
			</li>
	
			<li class="announcements">
				<%= render 'places/announcements/count' %>
			</li>
	
			<li class="comments">
				<%= render 'places/comments/count' %>
			</li>
			
			
		</ul>

		<div id="tabbed-content">
			<% unless @place.category.meta_survey.nil? %>
				<%= render 'places/evaluations/listing' %>
			<% end %>
		</div>
	</div>
</div>

<div id="map-box">
	<div style="width:220px; height:500px;" id="map" class="displays-points radio-3 rounded-5 shadow-lighter"></div>
</div>



<% unless @place.coordinates.nil? %>
	<%= hidden_field_tag 'coordinates[lat]', @place.coordinates.lat %>
	<%= hidden_field_tag 'coordinates[lon]', @place.coordinates.lon %>
<% end %>